# Generated by Django 2.2.2 on 2019-07-09 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lazypixels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lazypixels',
            name='path',
        ),
    ]
