# Generated by Django 2.2.2 on 2019-07-09 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lazypixels', '0002_remove_lazypixels_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lazypixels',
            name='timestamp',
        ),
    ]
